In [1]:
import scipy.stats as stats

In [2]:
import pandas as pd

In [3]:
import numpy as np
import seaborn as sns

In [4]:
dataset=sns.load_dataset("tips")

In [5]:
dataset.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [6]:
dataset_table=pd.crosstab(dataset["sex"],dataset["smoker"])
print(dataset_table)

smoker  Yes  No
sex            
Male     60  97
Female   33  54


In [7]:
dataset_table.values

array([[60, 97],
       [33, 54]], dtype=int64)

In [8]:
# Observed value

In [9]:
Observed_Values=dataset_table.values
print("Observed Values :-\n",Observed_Values)

Observed Values :-
 [[60 97]
 [33 54]]


In [10]:
val=stats.chi2_contingency(dataset_table)

In [11]:
val

(0.0,
 1.0,
 1,
 array([[59.84016393, 97.15983607],
        [33.15983607, 53.84016393]]))

In [12]:
no_of_rows=len(dataset_table.iloc[0:2,0])
no_of_columns=len(dataset_table.iloc[0,0:2])

In [13]:
no_of_rows

2

In [14]:
no_of_columns

2

In [16]:
ddof=(no_of_rows-1)*(no_of_columns-1)

ddof

1