In [1]:
import numpy as np

In [2]:
lst1=[1,2,3,4,5]

In [3]:
arr=np.array(lst1)

In [4]:
arr

array([1, 2, 3, 4, 5])

In [5]:
type(arr)

numpy.ndarray

In [6]:
arr.shape

(5,)

In [11]:
lst1=[1,2,3,4,5,6,7]
lst2=[8,9,10,11,12,13,25]
lst3=[34,44,56,21,10,2,12]
arr1=np.array([lst1,lst2,lst3])

In [12]:
arr1

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 25],
       [34, 44, 56, 21, 10,  2, 12]])

In [13]:
lst1=[1,2,3,4,5]
lst2=[2,3,4,5,6]
lst3=[3,4,5,6,7]
arr2=np.array([lst1,lst2,lst3])

In [14]:
arr2

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [15]:
arr1.shape

(3, 7)

In [16]:
 1

1

In [17]:
2

2

In [18]:
3

3

In [19]:
4

4

In [20]:
5

5

In [21]:
6

6

In [22]:
7

7

In [23]:
8

8

In [24]:
9

9

In [25]:
10

10

In [26]:
11

11

In [27]:
12

12

In [28]:
13

13

In [29]:
14

14

In [30]:
15

15

In [31]:
16

16

In [32]:
17

17

In [33]:
18

18

In [34]:
19

19

In [35]:
20

20

In [36]:
21

21

In [37]:
22

22

In [38]:
23

23

In [39]:
24

24

In [40]:
25

25

In [41]:
26

26

In [42]:
27

27

In [43]:
28

28

In [44]:
29

29