In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
df=pd.read_excel("C:\\Users\\rcmlp.12\\Desktop\\pirep delay\\EFG-E75_delay_piprep_data.xlsx")

In [4]:
df.head()

New_ata_code  MONTH_CODE  Pirep  Inte
0            23      201801     33     5
1            23      201802     47     9
2            23      201803     59    10
3            23      201804     61    17
4            23      201805     41     7

In [5]:
X=df.iloc[:,2:3]
y=df.iloc[:,3:4]
X


Pirep
0       33
1       47
2       59
3       61
4       41
..     ...
235     77
236     63
237     58
238     54
239     64

[240 rows x 1 columns]

In [6]:
y

Inte
0       5
1       9
2      10
3      17
4       7
..    ...
235    28
236    29
237    14
238    12
239    23

[240 rows x 1 columns]

In [7]:
print("Shape of X=",X.shape)
print("Shape of y=",y.shape)

Shape of X= (240, 1)
Shape of y= (240, 1)


In [8]:
from sklearn.model_selection import train_test_split

In [9]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2, random_state=51)

In [10]:
print("Shape of X_train=",X_train.shape)
print("Shape of X_test=",X_test.shape)
print("Shape of y_train=",y_train.shape)
print("Shape of y_test=",y_test.shape)

Shape of X_train= (192, 1)
Shape of X_test= (48, 1)
Shape of y_train= (192, 1)
Shape of y_test= (48, 1)


In [11]:
from sklearn.svm import SVC

In [12]:
classification_rbf=SVC(kernel='rbf')

In [13]:
classification_rbf.fit(X_train,y_train)

C:\Users\rcmlp.12\Anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC()

In [14]:
classification_rbf.score(X_test,y_test)

0.020833333333333332

In [15]:
from sklearn.preprocessing import StandardScaler

In [16]:
sc=StandardScaler()

In [17]:
sc.fit(X_train)


StandardScaler()

In [18]:
sc.fit

<bound method StandardScaler.fit of StandardScaler()>

In [19]:
X_train_sc=sc.transform(X_train)

In [20]:
X_test_sc=sc.transform(X_test)

In [21]:
classification_rbf_2=SVC(kernel='rbf')

In [22]:
classification_rbf_2.fit(X_train,y_train)

C:\Users\rcmlp.12\Anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC()

In [23]:
classification_rbf_2.score(X_test_sc,y_test)

C:\Users\rcmlp.12\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


0.020833333333333332

In [24]:
classification_rbf_2=SVC(kernel='rbf')
classification_rbf_2.fit(X_train,y_train)
classification_rbf_2.score(X_test_sc,y_test)

C:\Users\rcmlp.12\Anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\rcmlp.12\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


0.020833333333333332

In [25]:
classification_poly=SVC(kernel='poly',degree=2)
classification_poly.fit(X_train,y_train)
classification_poly.score(X_test_sc,y_test)

C:\Users\rcmlp.12\Anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\rcmlp.12\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


0.020833333333333332

In [26]:
classification_poly=SVC(kernel='poly',degree=3)
classification_poly.fit(X_train,y_train)
classification_poly.score(X_test_sc,y_test)

C:\Users\rcmlp.12\Anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\rcmlp.12\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


0.020833333333333332

In [27]:
classification_linear=SVC(kernel='linear')
classification_linear.fit(X_train,y_train)
classification_linear.score(X_test_sc,y_test)

C:\Users\rcmlp.12\Anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\rcmlp.12\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


0.020833333333333332

In [28]:
classification_linear.predict(X_test)

array([10, 10,  4, 10, 10,  9, 10, 10, 10, 14, 10, 10, 10, 10, 10, 45,  9,
       10, 35,  9, 10,  9,  9, 10, 25, 10,  9, 10, 35,  9, 35, 10, 10, 35,
       10, 10, 10, 35, 10, 10, 10, 10, 10, 10, 10, 10, 10,  2],
      dtype=int64)

In [29]:
classification_poly.predict(X_test)

array([10, 10, 10, 10, 11, 10, 10, 11, 10, 10, 10, 10, 10, 10, 10, 45, 10,
       10, 35, 10, 10, 10, 10, 10, 25, 10, 10, 11, 35, 10, 35, 10, 10, 25,
       10, 10, 10, 35, 10, 11, 11, 10, 10, 10, 10, 10, 10, 10],
      dtype=int64)

In [30]:
classification_rbf_2.predict(X_test)

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 45, 10,
       10, 35, 10, 10, 10, 10, 10, 35, 10, 10, 10, 35, 10, 35, 10, 10, 35,
       10, 10, 10, 35, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
      dtype=int64)